import { ClinicalCase } from "./index";

export const sampleSepsisCase: ClinicalCase = {
  id: "case-sepsis-001",
  slug: "elderly-postop-septic-shock",
  title: "Clinical Scenario: Acute Deterioration Following Hemicolectomy",
  subtitle: "72-Year-Old Female with Post-Operative Sepsis Progressing to Septic Shock",
  specialty: "Critical Care",
  targetExam: "Both",
  difficulty: "High",
  estimatedMinutes: 20,
  ehr: {
    patientProfile: {
      name: "Eleanor Vance",
      mrn: "MRN-8492019",
      age: 72,
      gender: "Female",
      admitDate: "2026-09-05",
      allergies: ["Penicillins (Anaphylaxis)", "Sulfa Drugs (Rash)"],
      codeStatus: "Full Code",
      weightKg: 64,
      attendingPhysician: "Dr. Robert Chen, MD (General Surgery)",
      diagnosis: "Post-op Day 2 Left Hemicolectomy for Diverticular Stricture",
    },
    nursesNotes: [
      {
        id: "note-1",
        timestamp: "07:00 (Post-Op Day 2)",
        author: "Sarah Jenkins, RN",
        role: "Night Shift Primary Nurse",
        content:
          "Patient resting in bed. Surgical dressing over midline incision dry and intact with small amount of serosanguineous drainage noted on outer border. Bowel sounds hypoactive in all 4 quadrants. Patient reports abdominal pain 4/10 managed with scheduled IV acetaminophen. Jackson-Pratt drain #1 has 40 mL serosanguineous fluid. Urine output overnight 320 mL clear yellow.",
      },
      {
        id: "note-2",
        timestamp: "11:30",
        author: "Marcus Rivera, RN",
        role: "Day Shift Primary Nurse",
        content:
          "Patient called complaining of sudden rigors and nausea. Flushed appearance noted. Surgical incision examined: dressing remains intact, but lower abdomen is tense, warm, and exquisitely tender to gentle palpation. Guarding noted. Jackson-Pratt drain output has changed to cloudy, purulent fluid with foul odor, volume 85 mL over the past 4 hours. Patient reports feeling dizzy and 'confused about where she is.'",
        highlightableSegments: [
          { id: "cue-1", text: "sudden rigors and nausea", isAbnormalCue: true },
          { id: "cue-2", text: "Flushed appearance noted", isAbnormalCue: true },
          { id: "cue-3", text: "lower abdomen is tense, warm, and exquisitely tender to gentle palpation", isAbnormalCue: true },
          { id: "cue-4", text: "Guarding noted", isAbnormalCue: true },
          { id: "cue-5", text: "cloudy, purulent fluid with foul odor", isAbnormalCue: true },
          { id: "cue-6", text: "feeling dizzy and 'confused about where she is'", isAbnormalCue: true },
        ],
      },
      {
        id: "note-3",
        timestamp: "13:00",
        author: "Marcus Rivera, RN",
        role: "Day Shift Primary Nurse",
        content:
          "Rapid Response Team (RRT) notified and at bedside. Patient is lethargic, responds only to loud verbal stimuli. Skin is warm and peripherally vasodilated with bounding peripheral pulses. Capillary refill brisk at 2 seconds. Foley catheter unkinked; 20 mL concentrated dark amber urine drained over last 2 hours. Surgical resident and intensivist evaluating for anastomotic leak and emergency laparotomy.",
        highlightableSegments: [
          { id: "cue-7", text: "lethargic, responds only to loud verbal stimuli", isAbnormalCue: true },
          { id: "cue-8", text: "warm and peripherally vasodilated", isAbnormalCue: true },
          { id: "cue-9", text: "20 mL concentrated dark amber urine drained over last 2 hours", isAbnormalCue: true },
        ],
      },
    ],
    vitals: [
      {
        timestamp: "07:00",
        bp: "126/78",
        hr: 76,
        rr: 16,
        temp: 98.6,
        tempUnit: "°F",
        spo2: 98,
        o2Delivery: "Room Air",
        painScore: "4/10",
      },
      {
        timestamp: "11:30",
        bp: "96/54",
        isBpAbnormal: true,
        hr: 118,
        isHrAbnormal: true,
        rr: 24,
        isRrAbnormal: true,
        temp: 102.6,
        tempUnit: "°F",
        isTempAbnormal: true,
        spo2: 93,
        isSpo2Abnormal: true,
        o2Delivery: "Room Air",
        painScore: "8/10",
      },
      {
        timestamp: "13:00",
        bp: "82/42",
        isBpAbnormal: true,
        hr: 132,
        isHrAbnormal: true,
        rr: 28,
        isRrAbnormal: true,
        temp: 103.1,
        tempUnit: "°F",
        isTempAbnormal: true,
        spo2: 90,
        isSpo2Abnormal: true,
        o2Delivery: "2 L/min NC",
        painScore: "Unresponsive to pain rating",
      },
    ],
    labs: [
      {
        category: "Hematology",
        testName: "White Blood Cells (WBC)",
        value: "22.4",
        numericValue: 22.4,
        unit: "x10³/µL",
        referenceRange: "4.5 - 11.0",
        flag: "H",
      },
      {
        category: "Hematology",
        testName: "Bands (Immature Granulocytes)",
        value: "16",
        numericValue: 16,
        unit: "%",
        referenceRange: "0 - 5",
        flag: "H",
      },
      {
        category: "Hematology",
        testName: "Hemoglobin",
        value: "11.8",
        numericValue: 11.8,
        unit: "g/dL",
        referenceRange: "12.0 - 15.5",
        flag: "L",
      },
      {
        category: "Hematology",
        testName: "Platelets",
        value: "98",
        numericValue: 98,
        unit: "x10³/µL",
        referenceRange: "150 - 450",
        flag: "L",
      },
      {
        category: "Chemistry",
        testName: "Serum Lactate",
        value: "4.6",
        numericValue: 4.6,
        unit: "mmol/L",
        referenceRange: "0.5 - 2.0",
        flag: "CRITICAL",
      },
      {
        category: "Chemistry",
        testName: "Serum Creatinine",
        value: "2.3",
        numericValue: 2.3,
        unit: "mg/dL",
        referenceRange: "0.6 - 1.2",
        flag: "H",
      },
      {
        category: "Chemistry",
        testName: "Blood Urea Nitrogen (BUN)",
        value: "38",
        numericValue: 38,
        unit: "mg/dL",
        referenceRange: "7 - 20",
        flag: "H",
      },
      {
        category: "Chemistry",
        testName: "Serum Potassium",
        value: "4.9",
        numericValue: 4.9,
        unit: "mEq/L",
        referenceRange: "3.5 - 5.0",
        flag: "NORMAL",
      },
      {
        category: "Arterial Blood Gas",
        testName: "pH",
        value: "7.28",
        numericValue: 7.28,
        unit: "",
        referenceRange: "7.35 - 7.45",
        flag: "L",
      },
      {
        category: "Arterial Blood Gas",
        testName: "HCO3 (Bicarbonate)",
        value: "15",
        numericValue: 15,
        unit: "mEq/L",
        referenceRange: "22 - 26",
        flag: "L",
      },
    ],
    orders: [
      {
        id: "ord-1",
        timestamp: "13:05",
        orderType: "Diagnostic",
        description: "Blood Cultures x2 sets from two distinct venipuncture sites STAT (prior to antimicrobial initiation)",
        urgency: "STAT",
        status: "Active",
      },
      {
        id: "ord-2",
        timestamp: "13:05",
        orderType: "Medication",
        description: "0.9% Normal Saline IV bolus 30 mL/kg (1,920 mL total) administered over 60 minutes via pressure bag",
        urgency: "STAT",
        route: "IV Infusion",
        status: "Active",
      },
      {
        id: "ord-3",
        timestamp: "13:10",
        orderType: "Medication",
        description: "Vancomycin 1.25 g IV every 12 hours (dose adjusted for renal clearance) AND Ciprofloxacin 400 mg IV every 12 hours (penicillin-allergic)",
        urgency: "STAT",
        route: "IV Piggyback",
        status: "Pending Pharmacy Verification",
      },
      {
        id: "ord-4",
        timestamp: "13:10",
        orderType: "Nursing Intervention",
        description: "Insert 16 Fr indwelling urinary catheter to gravity; maintain hourly strict urometer measurements (goal >0.5 mL/kg/hr)",
        urgency: "STAT",
        status: "Active",
      },
      {
        id: "ord-5",
        timestamp: "13:15",
        orderType: "Diagnostic",
        description: "Repeat venous lactate level in 2 hours following completion of fluid resuscitation",
        urgency: "Routine",
        status: "Active",
      },
    ],
  },
  questions: [
    {
      id: "q-sepsis-1",
      stepNumber: 1,
      stepName: "recognize_cues",
      title: "Step 1: Recognize Cues",
      type: "highlight",
      prompt:
        "Review the Nurses' Notes and Vital Signs at 11:30 and 13:00. Click on the 4 clinical findings below that represent acute indications of systemic tissue hypoperfusion and life-threatening decompensation.",
      instructionNote: "Select exactly 4 cues. Credit is awarded based on NCSBN +/- scoring rules.",
      maxScore: 4,
      scoringMethod: "+/-",
      textSegments: [
        { id: "seg-1", text: "Blood pressure 82/42 mmHg (MAP 55 mmHg)", isCorrectCue: true },
        { id: "seg-2", text: "Serum lactate 4.6 mmol/L with metabolic acidosis (pH 7.28, HCO3 15)", isCorrectCue: true },
        { id: "seg-3", text: "Oliguria (20 mL urine output over last 2 hours / 0.15 mL/kg/hr)", isCorrectCue: true },
        { id: "seg-4", text: "Acute altered mental status (lethargy responding only to loud verbal stimuli)", isCorrectCue: true },
        { id: "seg-5", text: "Jackson-Pratt drain serosanguineous drainage 40 mL overnight", isCorrectCue: false },
        { id: "seg-6", text: "Bowel sounds hypoactive in all 4 quadrants on post-op day 2", isCorrectCue: false },
        { id: "seg-7", text: "Normal serum potassium of 4.9 mEq/L", isCorrectCue: false },
      ],
      rationale: {
        overview:
          "Recognizing the clinical hallmarks of severe sepsis and distributive septic shock is paramount. The patient demonstrates severe end-organ hypoperfusion across neurologic, renal, and hemodynamic systems.",
        pathophysiology:
          "Sepsis triggers widespread endothelial injury and cytokine storm (TNF-alpha, IL-1, IL-6), leading to profound peripheral vasodilation, microvascular thrombosis, increased capillary permeability, and cellular dysoxia. Inability of mitochondria to utilize oxygen drives anaerobic glycolysis, causing hyperlactatemia and metabolic acidosis.",
        clinicalPearl:
          "Mean Arterial Pressure (MAP) < 65 mmHg, serum lactate > 2.0 mmol/L, and oliguria (<0.5 mL/kg/hr) are prime diagnostic criteria for septic shock requiring immediate resuscitation.",
        optionsFeedback: {
          "seg-1": "Correct: Severe hypotension with MAP 55 mmHg indicates refractory loss of systemic vascular resistance.",
          "seg-2": "Correct: Critical lactate of 4.6 mmol/L reflects severe tissue cellular hypoxia.",
          "seg-3": "Correct: Urine output of 10 mL/hr in a 64 kg adult is severe oliguria reflecting acute tubular ischemia.",
          "seg-4": "Correct: Acute encephalopathy/lethargy is a recognized marker of cerebral hypoperfusion in sepsis.",
          "seg-5": "Incorrect: 40 mL of serosanguineous drainage on post-op day 2 is an expected post-surgical finding.",
          "seg-6": "Incorrect: Hypoactive bowel sounds are standard post-operative ileus on post-op day 2.",
          "seg-7": "Incorrect: A normal potassium level does not signify organ dysfunction.",
        },
      },
    },
    {
      id: "q-sepsis-2",
      stepNumber: 2,
      stepName: "analyze_cues",
      title: "Step 2: Analyze Cues",
      type: "matrix",
      prompt:
        "For each clinical assessment finding, select whether it is most consistent with Septic Shock (Distributive), Hypovolemic Shock (Hemorrhagic), or Expected Post-Operative Recovery.",
      instructionNote: "Each row must have exactly one selection.",
      maxScore: 4,
      scoringMethod: "0/1",
      columns: [
        { id: "col-septic", label: "Septic Shock (Distributive)" },
        { id: "col-hypovolemic", label: "Hypovolemic Shock (Hemorrhagic)" },
        { id: "col-normal", label: "Expected Post-Op Recovery" },
      ],
      rows: [
        {
          id: "row-1",
          finding: "Tense, tender abdomen with foul purulent JP drain fluid and high fever (103.1°F)",
          correctColumnId: "col-septic",
        },
        {
          id: "row-2",
          finding: "Warm, flushed extremities with bounding peripheral pulses despite MAP of 55 mmHg",
          correctColumnId: "col-septic",
        },
        {
          id: "row-3",
          finding: "Mild incisional pain (4/10) responsive to scheduled acetaminophen",
          correctColumnId: "col-normal",
        },
        {
          id: "row-4",
          finding: "Profound pallor, cold clammy extremities, flat neck veins, and acute drop in Hgb > 4 g/dL",
          correctColumnId: "col-hypovolemic",
        },
      ],
      rationale: {
        overview:
          "Differentiating distributive septic shock from hemorrhagic hypovolemia is critical in a post-surgical patient. Early 'warm' septic shock is characterized by high cardiac output with low systemic vascular resistance (SVR), presenting with warm, flushed extremities and bounding pulses, unlike hemorrhagic shock where vasoconstriction causes cold, pale, clammy skin.",
        pathophysiology:
          "Purulent foul-smelling JP drain fluid coupled with peritoneal signs indicates an anastomotic breakdown leaking fecal flora into the peritoneal cavity (fecal peritonitis). The subsequent systemic endotoxin release causes profound peripheral nitric oxide release and vasodilation.",
        clinicalPearl:
          "Warm peripheries with bounding pulses in a hypotensive patient point directly to distributive (septic) shock, not hemorrhagic shock.",
        optionsFeedback: {
          "row-1": "Peritonitis and purulent drainage with hyperthermia directly indicate intra-abdominal sepsis.",
          "row-2": "Hyperdynamic warm shock with low SVR is the hallmark of distributive septic shock.",
          "row-3": "Mild baseline discomfort controlled by non-opioid analgesics is standard recovery.",
          "row-4": "Pallor, cold clammy skin, and severe acute anemia characterize hypovolemic/hemorrhagic shock.",
        },
      },
    },
    {
      id: "q-sepsis-3",
      stepNumber: 3,
      stepName: "prioritize_hypotheses",
      title: "Step 3: Prioritize Hypotheses",
      type: "drag_priority",
      prompt:
        "Based on the clinical presentation, rank the following potential client problems in order of immediate priority (Rank 1 being the highest priority threat to life).",
      instructionNote: "Arrange all 4 items in sequence from highest priority to lowest priority.",
      maxScore: 4,
      scoringMethod: "0/1",
      items: [
        {
          id: "hypo-1",
          label: "Inadequate Systemic Tissue Perfusion",
          details: "Secondary to widespread vasodilation and capillary leakage (Septic Shock)",
          correctRank: 1,
        },
        {
          id: "hypo-2",
          label: "Impaired Gas Exchange / Acute Respiratory Failure",
          details: "Tachypnea (RR 28) and desaturation (SpO2 90%) secondary to metabolic acidosis and early ARDS",
          correctRank: 2,
        },
        {
          id: "hypo-3",
          label: "Acute Kidney Injury & Fluid Imbalance",
          details: "Oliguria and rising serum creatinine secondary to renal hypoperfusion",
          correctRank: 3,
        },
        {
          id: "hypo-4",
          label: "Acute Post-Surgical Incisional Discomfort",
          details: "Secondary to tissue injury and abdominal distension",
          correctRank: 4,
        },
      ],
      rationale: {
        overview:
          "Prioritizing hypotheses follows the ABCs (Airway, Breathing, Circulation) and survival threat. Systemic hypoperfusion with shock is an immediate cellular killer requiring resuscitation within minutes.",
        pathophysiology:
          "Circulatory failure in septic shock compromises blood flow to every vital organ. While respiratory support and renal protection are essential, without restoring systemic perfusion pressure (MAP >= 65), irreversible multi-organ dysfunction syndrome (MODS) will ensue.",
        clinicalPearl:
          "Circulation and systemic perfusion take precedence when MAP falls below critical autoregulation thresholds (65 mmHg), followed closely by oxygenation and ventilation support.",
        optionsFeedback: {
          "hypo-1": "Rank 1: Severe hypotension (MAP 55) and critical lactate require urgent volume resuscitation.",
          "hypo-2": "Rank 2: Gas exchange impairment and tachypnea must be monitored for ARDS and fatigue.",
          "hypo-3": "Rank 3: AKI is a downstream consequence of renal hypoperfusion.",
          "hypo-4": "Rank 4: Pain management is a priority only after hemodynamic stability and perfusion are restored.",
        },
      },
    },
    {
      id: "q-sepsis-4",
      stepNumber: 4,
      stepName: "generate_solutions",
      title: "Step 4: Generate Solutions",
      type: "cloze_dropdown",
      prompt: "Complete the clinical rationale sentence by choosing the appropriate options from each dropdown list.",
      instructionNote: "Both dropdowns must be answered correctly to earn rationale points.",
      maxScore: 2,
      scoringMethod: "rationale_dyad",
      prefixText: "To reverse refractory hypotension and cellular hypoperfusion, the nurse must urgently initiate ",
      dropdown1: {
        id: "drop-intervention",
        placeholder: "-- Select First-Line Intervention --",
        options: [
          { id: "opt-fluids", label: "an IV crystalloid bolus of 30 mL/kg within the first 3 hours" },
          { id: "opt-epi", label: "intramuscular epinephrine 0.5 mg in the anterolateral thigh" },
          { id: "opt-furosemide", label: "IV push furosemide 40 mg to stimulate urine production" },
          { id: "opt-dextrose", label: "50% dextrose IV bolus with 10 units regular insulin" },
        ],
        correctOptionId: "opt-fluids",
      },
      middleText: " because ",
      dropdown2: {
        id: "drop-rationale",
        placeholder: "-- Select Underlying Rationale --",
        options: [
          { id: "rat-perfusion", label: "restoring effective intravascular volume is essential to re-establish venous return, cardiac preload, and organ perfusion" },
          { id: "rat-anaphylaxis", label: "mast cell degranulation requires immediate beta-2 receptor activation and mucosal edema vasoconstriction" },
          { id: "rat-renal", label: "loop diuretics promote renal tubular flow and prevent acute tubular necrosis regardless of blood pressure" },
          { id: "rat-glucose", label: "cellular metabolic dysfunction in sepsis stems directly from intracellular glycogen depletion" },
        ],
        correctOptionId: "rat-perfusion",
      },
      suffixText: " before initiating vasopressors or surgical revision.",
      rationale: {
        overview:
          "Surviving Sepsis Campaign guidelines stipulate that for patients with sepsis-induced hypoperfusion or lactate >= 4.0 mmol/L, at least 30 mL/kg of IV crystalloid fluid must be given within the first 3 hours.",
        pathophysiology:
          "In septic shock, pathologic venodilation and diffuse capillary leakage create a massive deficit in effective circulating volume ('relative and absolute hypovolemia'). Rapid crystalloid administration expands intravascular volume, restoring cardiac filling pressures and cardiac output.",
        clinicalPearl:
          "Never administer loop diuretics (furosemide) in an oliguric hypotensive patient in septic shock; the oliguria is pre-renal due to volume depletion, and diuretics will precipitate cardiovascular collapse.",
        optionsFeedback: {
          "opt-fluids": "Correct: Surviving Sepsis Campaign standard of care is 30 mL/kg IV crystalloids for lactate >= 4 mmol/L or hypotension.",
          "opt-epi": "Incorrect: Epinephrine IM is the treatment for anaphylaxis, not septic shock.",
          "opt-furosemide": "Incorrect: Furosemide in a volume-depleted hypotensive patient accelerates circulatory collapse.",
          "opt-dextrose": "Incorrect: Insulin and dextrose are used for hyperkalemia, not septic shock resuscitation.",
        },
      },
    },
    {
      id: "q-sepsis-5",
      stepNumber: 5,
      stepName: "take_action",
      title: "Step 5: Take Action",
      type: "multiple_response",
      prompt:
        "The nurse is reviewing the provider's orders and clinical plan. Which actions should the nurse take immediately? Select all that apply.",
      instructionNote: "NCSBN Multiple Response (+/- scoring). Points are earned for correct selections and deducted for incorrect selections.",
      maxScore: 5,
      scoringMethod: "+/-",
      options: [
        {
          id: "act-1",
          label: "Obtain two sets of blood cultures from two separate venipuncture sites before starting antibiotics",
          isCorrect: true,
          rationaleSnippet: "Ensures pathogen identification without antibiotic interference.",
        },
        {
          id: "act-2",
          label: "Confirm patient allergy status and notify pharmacist of severe penicillin anaphylaxis before administering ordered empiric antimicrobials",
          isCorrect: true,
          rationaleSnippet: "Vital patient safety check to prevent fatal drug-induced anaphylaxis.",
        },
        {
          id: "act-3",
          label: "Place the patient in Trendelenburg position (head down 30 degrees) for the duration of the shift",
          isCorrect: false,
          rationaleSnippet: "Contraindicated: impairs diaphragmatic excursion, increases intracranial pressure, and does not improve sustained cardiac output.",
        },
        {
          id: "act-4",
          label: "Monitor hourly urine output using an in-dwelling urometer, targeting >= 0.5 mL/kg/hr",
          isCorrect: true,
          rationaleSnippet: "Sensitive non-invasive measure of renal cortical perfusion.",
        },
        {
          id: "act-5",
          label: "Administer the 30 mL/kg crystalloid bolus under pressure bag over 30 to 60 minutes",
          isCorrect: true,
          rationaleSnippet: "Rapid volume expansion is needed to restore venous return and MAP >= 65.",
        },
        {
          id: "act-6",
          label: "Hold all IV fluids until the patient completes a stat non-contrast CT scan of the abdomen",
          isCorrect: false,
          rationaleSnippet: "Dangerous delay: hemodynamic resuscitation must never be withheld for diagnostic imaging.",
        },
        {
          id: "act-7",
          label: "Prepare norepinephrine infusion if MAP remains < 65 mmHg despite adequate fluid resuscitation",
          isCorrect: true,
          rationaleSnippet: "First-line vasopressor of choice in septic shock to restore vascular tone.",
        },
      ],
      rationale: {
        overview:
          "Sepsis resuscitation requires timely, synchronized clinical actions: obtaining blood cultures prior to antimicrobials, administering weight-based fluid boluses, monitoring urine output, and preparing vasopressors (norepinephrine) for fluid-refractory hypotension.",
        pathophysiology:
          "Blood cultures taken prior to antibiotics preserve diagnostic yield. Delaying antibiotics for imaging or failing to check allergies can lead to fatal outcomes.",
        clinicalPearl:
          "Norepinephrine is the first-choice vasopressor in septic shock; phenylephrine or dopamine are second-line due to excessive vasoconstriction or tachyarrhythmias.",
        optionsFeedback: {
          "act-1": "Correct: Sepsis bundle requires blood cultures prior to antibiotic infusion.",
          "act-2": "Correct: The patient has a documented penicillin anaphylaxis history.",
          "act-3": "Incorrect: Trendelenburg position is outmoded and harmful to pulmonary mechanics.",
          "act-4": "Correct: Hourly urometer tracking detects early recovery or worsening of renal tubular perfusion.",
          "act-5": "Correct: 30 mL/kg fluid bolus must be infused rapidly, not run at maintenance rate.",
          "act-6": "Incorrect: Withholding resuscitation for imaging is life-threatening malpractice.",
          "act-7": "Correct: Norepinephrine is the first-line vasopressor to restore vascular tone.",
        },
      },
    },
    {
      id: "q-sepsis-6",
      stepNumber: 6,
      stepName: "evaluate_outcomes",
      title: "Step 6: Evaluate Outcomes",
      type: "evaluate_matrix",
      prompt:
        "Two hours following completion of the 1,920 mL IV crystalloid bolus and initiation of empiric antibiotics, the nurse reassesses the client. For each finding, determine whether the patient's condition is Improved, Unchanged, or Deteriorated.",
      instructionNote: "Select one outcome status per parameter.",
      maxScore: 4,
      scoringMethod: "0/1",
      parameters: [
        {
          id: "eval-1",
          parameter: "Hemodynamic Profile",
          finding: "Blood pressure 104/62 mmHg (MAP 76 mmHg), Heart Rate 94 bpm (down from 132 bpm)",
          correctStatus: "improved",
        },
        {
          id: "eval-2",
          parameter: "Metabolic Biomarker",
          finding: "Repeat serum lactate 2.4 mmol/L (down from 4.6 mmol/L)",
          correctStatus: "improved",
        },
        {
          id: "eval-3",
          parameter: "Neurologic Status",
          finding: "Patient oriented to person, hospital, and year; speech clear and appropriate",
          correctStatus: "improved",
        },
        {
          id: "eval-4",
          parameter: "Respiratory Dynamics",
          finding: "Respiratory rate 34 bpm, bilateral crackles in lower lung bases, SpO2 88% on 4 L nasal cannula",
          correctStatus: "deteriorated",
        },
      ],
      rationale: {
        overview:
          "Evaluating resuscitation requires assessing both therapeutic response and iatrogenic complications. While hemodynamic, metabolic, and neurologic parameters have improved, new-onset tachypnea, basilar crackles, and hypoxemia suggest fluid overload or transfusion/sepsis-related acute lung injury (ARDS).",
        pathophysiology:
          "Rapid crystalloid administration in elderly patients with capillary hyperpermeability can precipitate pulmonary hydrostatic edema and accelerate the progression toward Acute Respiratory Distress Syndrome (ARDS).",
        clinicalPearl:
          "Always monitor pulmonary status closely during large-volume resuscitation. Crackles, tachypnea, and worsening hypoxia require immediate assessment for non-cardiogenic pulmonary edema or cardiogenic fluid overload.",
        optionsFeedback: {
          "eval-1": "Improved: MAP > 65 mmHg and resolving tachycardia reflect improved stroke volume.",
          "eval-2": "Improved: Lactate clearance of > 20% in 2 hours is an established marker of therapeutic response.",
          "eval-3": "Improved: Resolution of encephalopathy indicates restored cerebral perfusion.",
          "eval-4": "Deteriorated: Worsening hypoxia and new crackles indicate pulmonary edema/ARDS.",
        },
      },
    },
  ],
};
